Algoritmo "Operadores Matematicos"

Var
      x, y, z: inteiro
      r: real
Inicio

      escreva("Digite um valor para X: ")
      leia(x)
      
      escreva("Digite um valor para y: ")
      leia(y)

      z <- X+y
      escreval(x, " + ", y, " = ", z)

      z <- z + x * y
      escreval("z = ",z)

      r <- z/2
      escreval("r = ",r)

      x <- 5
      y <- 2
      z <- x mod y
      escreval(x," mod ", y , z)

Fimalgoritmo