nome = input('Digite seu nome: ')
print('Seu nome é: {}'.format(nome.upper()))
print('Minuscula: {}'.format(nome.lower()))
nome.find(' ')
tam = len(nome.strip())
teste = nome.split()
teste2 = ''.join(teste)
print('A quantidade de letras sem considerar espaços no seu nome é: {}'.format(len(teste2)))
cont2 = (len(teste[0]))
print('A quantidade de letras do seu primeiro nome é: {}'.format(cont2))