#CREATE DATABASE AULA_O4;
CREATE TABLE FATECZL.EXEMPLO1(
ID INT,
CPF VARCHAR(45),
NOME_COMPLETO VARCHAR(255),
PRIMARY KEY(ID),
UNIQUE(CPF)
);
CREATE TABLE FATECZL.EXEMPLO02(
ID INT, 
APELIDO VARCHAR(255) NOT NULL,
ID_NOME INT,
PRIMARY KEY (ID),
FOREIGN KEY(ID_NOME) REFERENCES EXEMPLO1(ID),
);